import Head from 'next/head'
import Hero from '../components/Hero';
import Posts from '../components/Posts';
import prisma from '../lib/prisma'

export default function Home({ feed }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className='text-lg font-semibold text-center'>
          <Posts feeds={feed}/>
        </div>
      </main>
    </div>
  )
}

// index.js
export const getStaticProps = async () => {
  const feed = await prisma.post.findMany({
    where: { published: true },
    include: {
      author: {
        select: { name: true },
      },
    },
  });
  return { props: { feed } };
}